services:
  redis:
    image: redis:alpine
    container_name: veda_redis
    ports:
      - "6379:6379"
    volumes:
      # This maps the data inside the container to a folder on your laptop
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: veda_redis_ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

# Define the volume explicitly
volumes:
  redis_data: